[config]
mode = "dark"

[config.custom_colors]
amanojaku = { color = "#00ff11", blend = false }
amanojaku_black = { color = "#000000", blend = false }
amanojaku_gray_1 = { color = "#333333", blend = false }
amanojaku_gray_2 = { color = "#555555", blend = false }
amanojaku_gray_3 = { color = "#777777", blend = false }
amanojaku_gray_4 = { color = "#999999", blend = false }
amanojaku_white = { color = "#ffffff", blend = false }
amanojaku_white_1 = { color = "#aaaaaa", blend = false }
amanojaku_red = { color = "#ff0000", blend = false }
amanojaku_lualine_red = { color = "#aa1100", blend = false }
amanojaku_lualine_green = { color = "#11aa00", blend = false }
amanojaku_lualine_blue = { color = "#1100aa", blend = false }
amanojaku_lualine_yellow = { color = "#ffcc00", blend = false }

[config.wallpaper]
command = 'awww'
arguments = ['img', '--transition-type', 'random', '--transition-step', '90', 'transition-fps', '60']
set = true

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/themes/colors.css"
post_hook = "~/.config/waybar/scripts/launch.sh"

[templates.cava]
input_path = '~/.config/matugen/templates/cava-cus.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = "pkill -USR2 cava"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/themes/colors.css"
post_hook = "swaync-client -rs"
