$Weather = ~/.config/hypr/hyprlock/scripts/weather.sh

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 7
    brightness = 0.8
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 0
    outer_color = rgb(255, 255, 255) 
    dots_size = 0.3 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgb(0, 0, 0)
    font_family = JetBrainsMono Nerd Font Mono ExtraBold
    font_color = rgb(0, 255, 0)
    fade_on_empty = true
    placeholder_text = PASS >_<
    hide_input = false
    position = 0, -470
    halign = center
    valign = center
    zindex = 20
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = rgba(255, 255, 255, 1)
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2
    font_size = 150
    font_family = JetBrainsMono Nerd Font Mono 
    position = 0, -250
    halign = center
    valign = top
    zindex = 5
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(255, 255, 255, 1)
    font_size = 150
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, -420
    halign = center
    valign = top
    zindex = 5
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = rgba(255, 255, 255, 1)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -130
    halign = center
    valign = center
    zindex = 5
}

# USER-BOX
shape {
    monitor =
    size = 250, 60
    color = rgba(255, 255, 255, 0.1)
    rounding = -1
    border_size = 0
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 0, -400
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =  $USER
    color = rgb(255, 255, 255)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 20
    font_family = JetBrainsMono Nerd Font Mono Bold
    position = 0, -400
    halign = center
    valign = center
}


# Weather div

# WEATHER 
label {
    monitor =
    text = cmd[update:1000] $Weather
    color = rgb(255, 255, 255)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 40, -20
    halign = left
    valign = top
    zindex = 5
}


# Battery div
shape {
    monitor =
    size = 80, 32
    color =rgba(0, 0, 0, 0.5)
    rounding = 20
    rotate = 0
    position = -30, -18
    halign = right
    valign = top
    zindex = 1
}

# Battery
label {
    monitor =
    text = cmd[update:30000] echo "󰁹 $(cat /sys/class/power_supply/BAT0/capacity)%"
    color = rgb(255, 255, 255)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -40 , -20 
    halign = right
    valign = top
    zindex = 5
}

image {
    monitor =
    path = ~/.face/araragi.jpg
    size = 120 # Size of the avatar
    rounding = -1 # Negative means a perfect circle
    border_size = 4
    border_color = rgb(221, 221, 221)
    rotate = 0 # Degrees
    reload_time = -1 # Seconds between reloads (-1 means never)

    position = 0, -290
    halign = center
    valign = center
}

